Added RetroPage2 component with some CSS and  tested with App.js
HackYourFuture-CPH/team26-RetroRealm pull request #11
Opened 2024-04-03 23:05 UTC by SpartanDeBoss

# Description
* Retro page 2
Please provide a short summary explaining what this PR is about.
* Some functionality to join a retro or to start a new retro
Fixes # (issue)

# How to test?
* yarn start
Please provide a short summary how your changes can be tested?
* It can be tested yet still have some functionality to add and make it work.
# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2024-04-04 06:10 UTC, shpomp commented
@SpartanDeBoss  fix the build fail. 
See the error, it is related to Prettier and check scripts in package.json to see what to run 💡

2024-04-04 09:08 UTC, SpartanDeBoss commented
> @SpartanDeBoss fix the build fail. See the error, it is related to Prettier and check scripts in package.json to see what to run 💡

it seems my prettier was not functioning so i disabled and enabled it after (formatting) the magic worked Thanks! @shpomp

2024-04-04 16:03 UTC, DanJecu requested changes
Good job Aaron 💪🏻 

I left you some comments to resolve.

2024-04-04 16:03 UTC, DanJecu commented on packages/client/src/containers/RetroPageSecond/RetroPage2.jsx
> +              <select className="roleSelect">
This one is not working. Could you figure out why?

2024-04-07 16:37 UTC, DanJecu requested changes
Names of components and functions should provide clarity, enabling you to navigate the code. So, if your app is a Retro app, it seems like `RetroPage` should be the `HomePage`, and `RetroPage2` should actually be `RetroPage`.
You can also call `RetroPage` --> `JoinRetroPage` & `RetroPage2` coud be `RetroPage`.

2024-04-08 18:37 UTC, SpartanDeBoss commented
I have resolved those changes.

2024-04-08 18:53 UTC, DanJecu approved these changes

2024-04-08 19:19 UTC, merged